name: Fetch and Release Prefixes

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight UTC

jobs:
  fetch-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'
          check-latest: true

      - name: Run go mod tidy
        run: go mod tidy

      - name: Fetch IR prefixes
        run: go run . --fetch-ir --verbose

      - name: Fetch CN prefixes
        run: go run . --fetch-cn --verbose

      - name: Set release variables
        run: |
          echo "RELEASE_TAG=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "RELEASE_DATE=$(date -u +'%A %F %T %Z')" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.RELEASE_TAG }}
          tag_name: ${{ env.RELEASE_TAG }}
          draft: false
          prerelease: false
          files: |
            ir_prefixes_v4.txt
            ir_prefixes_v6.txt
            cn_prefixes_v4.txt
            cn_prefixes_v6.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean older releases
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          keep_latest: 30
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
