name: Fetch And Commit

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight (UTC)
  workflow_dispatch:

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      CGO_ENABLED: 0

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.5'
        check-latest: true

    - name: Download Go modules
      run: go mod download

    - name: Set timestamp
      run: echo "TIMESTAMP=$(date -u +"%H:%M %d-%m-%Y")" >> $GITHUB_ENV

    - name: Fetch IR prefixes
      run: go run . --fetch-ir --verbose

    - name: Fetch CN prefixes
      run: go run . --fetch-cn --verbose

    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Auto-Update - ${{ env.TIMESTAMP }}"
        file_pattern: 'ir_prefixes_v4.txt ir_prefixes_v6.txt cn_prefixes_v4.txt cn_prefixes_v6.txt'
